@host = https://localhost:7188

@id = 61c7288b-2c3a-4d11-9f42-53cb374bd54f

POST {{host}}/api/monthlyBillings/{{id}}/plans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImNhMjI5Mzk3LThkMzgtNDQ5MS05NmI2LWU3YmJjMjM5YTc5YyIsImp0aSI6IjdlOGIyMDBhLTM0ODktNGYwOC04YjFiLTI2YWJjZDI2ZjI3YiIsImVtYWlsIjoicGFua3VuaWsyQHBhbmt1bmlrLnBsIiwiaWQiOiJjYTIyOTM5Ny04ZDM4LTQ0OTEtOTZiNi1lN2JiYzIzOWE3OWMiLCJuYmYiOjE2OTgyOTQ1NDQsImV4cCI6MTY5ODI5NDg0NCwiaXNzIjoic211Z2V0LWlzc3VlciIsImF1ZCI6InNtdWdldC1hdWRpZW5jZSJ9.LwLC8LD1YbWvc1Hd4Rw6wFmj1xB153p2oB3-SbJU5WE
Content-Type: application/json

{
    "category": "Groceries",
    "money": 450,
    "currency": "PLN",
    "sortOrder": 1
}