@host = https://localhost:7188

@monthlyBillingId = eb8409a9-af87-4fa5-bc4d-aa7b1701c8be
@planId = 06dd5170-6339-421f-b7da-9919650b4689

POST {{host}}/api/monthlyBillings/{{monthlyBillingId}}/plans/{{planId}}/expenses
Content-Type: application/json

{
    "money": 73.14,
    "currency": "PLN",
    "expenseDate": "2023-08-15T17:33:17+00:00",
    "description": "Allegra"
}