@host = https://localhost:7188

@id = eb8409a9-af87-4fa5-bc4d-aa7b1701c8be

POST {{host}}/api/monthlyBillings/{{id}}/incomes
Content-Type: application/json

{
    "name": "Zwrot",
    "moneyAmount": 108.25,
    "currency": "PLN",
    "includeInBilling": true
}