@host = https://localhost:7188

@id = 4bcfbe2e-0a4b-4c3a-ba27-cfba56c0a319

POST {{host}}/api/monthlyBillings/{{id}}/incomes
Content-Type: application/json

{
    "name": "Earn",
    "moneyAmount": 5247.43,
    "currency": 1,
    "includeInBilling": true
}