@host = https://localhost:7188

@id = 820db3c1-70b7-484a-b4f4-4304bb62d32a

POST {{host}}/api/monthlyBillings/{{id}}/incomes
Content-Type: application/json

{
    "name": "Wypłata",
    "moneyAmount": 7778,
    "currency": "PLN",
    "includeInBilling": true
}