@host = https://localhost:7188

@id = 820db3c1-70b7-484a-b4f4-4304bb62d32a

POST {{host}}/api/monthlyBillings/{{id}}/plans
Content-Type: application/json

{
    "category": "Test 2",
    "money": 123.45,
    "currency": "PLN",
    "sortOrder": 5
}