@host = https://localhost:7188

@id = eb8409a9-af87-4fa5-bc4d-aa7b1701c8be

POST {{host}}/api/monthlyBillings/{{id}}/plans
Content-Type: application/json

{
    "category": "Leki",
    "money": 200,
    "currency": "PLN",
    "sortOrder": 1
}