@host = https://localhost:7188

@id = f26ff0b4-a1ad-4517-b78e-2ed1c34c808f

POST {{host}}/api/monthlyBillings/{{id}}/plans
Content-Type: application/json

{
    "category": "Rozrywka",
    "money": 350,
    "currency": "PLN",
    "sortOrder": 5
}