@host = https://localhost:7188

POST {{host}}/api/monthlyBillings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjM0NDY0MDU2LWUzYWQtNDZjZi04N2RkLWNhOWVkY2VmM2VlZSIsImp0aSI6IjMyYjE2ZmNjLTI4NDYtNGZmZS1iN2E5LTkxNGJhMDI3NWI0MiIsImVtYWlsIjoicGFua3VuaWtAcGFua3VuaWsucGwiLCJpZCI6IjM0NDY0MDU2LWUzYWQtNDZjZi04N2RkLWNhOWVkY2VmM2VlZSIsIm5iZiI6MTY5Nzc0NTgxNiwiZXhwIjoxNjk3NzQ1ODYxLCJpc3MiOiJzbXVnZXQtaXNzdWVyIiwiYXVkIjoic211Z2V0LWF1ZGllbmNlIn0.2Y55MEcQPy8ed1hm_CEUp5AiIgcsoAIWfe43kbw2SQ0
Content-Type: application/json

{
    "Year": 2023,
    "Month": 10,
    "Currency": "PLN"
}