@host = https://localhost:7188
# RefreshToken = UgT7dAUyhpgqJak8S+Ohxp7SIOVTuzkODzRv/L6Uj7YtWnLgAxfrDuswng2WwBomgKYisne92NJ+5en1qzKrWw==

POST {{host}}/api/monthlyBillings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjM0NDY0MDU2LWUzYWQtNDZjZi04N2RkLWNhOWVkY2VmM2VlZSIsImp0aSI6Ijk5N2M3ZmI2LTJlOWUtNGI4Ny1hN2MyLTdjOTMyOWZhNGRmMCIsImVtYWlsIjoicGFua3VuaWtAcGFua3VuaWsucGwiLCJpZCI6IjM0NDY0MDU2LWUzYWQtNDZjZi04N2RkLWNhOWVkY2VmM2VlZSIsIm5iZiI6MTY5NzY1NDIwNCwiZXhwIjoxNjk3NjU0MjM0LCJpc3MiOiJzbXVnZXQtaXNzdWVyIiwiYXVkIjoic211Z2V0LWF1ZGllbmNlIn0.0Necg3uYna4cF1RRrqmWwHdvB2Xsd3MXgfM5CVMSIjM
Content-Type: application/json

{
    "Year": 2023,
    "Month": 10,
    "Currency": "PLN"
}