@host = https://localhost:7188
@year = 2023
@month = 10

PUT {{host}}/api/monthlyBillings/{{year}}/{{month}}/reopen
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjM0NDY0MDU2LWUzYWQtNDZjZi04N2RkLWNhOWVkY2VmM2VlZSIsImp0aSI6ImFkYTllOGRkLTU4OTMtNDIyNi1iZjEwLWJkOTYwMjI3NWMzNiIsImVtYWlsIjoicGFua3VuaWtAcGFua3VuaWsucGwiLCJpZCI6IjM0NDY0MDU2LWUzYWQtNDZjZi04N2RkLWNhOWVkY2VmM2VlZSIsIm5iZiI6MTY5Nzc0Mjk4NSwiZXhwIjoxNjk3NzQzMDMwLCJpc3MiOiJzbXVnZXQtaXNzdWVyIiwiYXVkIjoic211Z2V0LWF1ZGllbmNlIn0.cq-HE9SR1qkjgJH4IifcZ8_Y1Z7AnEC0fbMQZj6iqhQ