@host = https://localhost:7188
@year = 2023
@month = 10

PUT {{host}}/api/monthlyBillings/{{year}}/{{month}}/reopen
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1N2E5YjNlYi0xNzk2LTRlMGQtYTZiNC1mYzEwYmQzZjkzYjIiLCJ1bmlxdWVfbmFtZSI6IjU3YTliM2ViLTE3OTYtNGUwZC1hNmI0LWZjMTBiZDNmOTNiMiIsIm5iZiI6MTY5NzE0MjQ0NiwiZXhwIjoxNjk3MTQzNjQ2LCJpc3MiOiJzbXVnZXQtaXNzdWVyIiwiYXVkIjoic211Z2V0LWF1ZGllbmNlIn0.KRKiFKHdfnHARjn7QbLZelx4lRukhCXXpYVTHd0TZhQ
