@host = https://localhost:7188
@year = 2023
@month = 10

PUT {{host}}/api/monthlyBillings/{{year}}/{{month}}/reopen
eyJ1bmlxdWVfbmFtZSI6IjM0NDY0MDU2LWUzYWQtNDZjZi04N2RkLWNhOWVkY2VmM2VlZSIsImp0aSI6IjRmYTMyMTJmLTZjY2UtNDQ0MC04MzEwLWJlOTMwMmM3NDFkNCIsImVtYWlsIjoicGFua3VuaWtAcGFua3VuaWsucGwiLCJpZCI6IjM0NDY0MDU2LWUzYWQtNDZjZi04N2RkLWNhOWVkY2VmM2VlZSIsIm5iZiI6MTY5NzY1MTM2OCwiZXhwIjoxNjk3NjUxMzk4LCJpc3MiOiJzbXVnZXQtaXNzdWVyIiwiYXVkIjoic211Z2V0LWF1ZGllbmNlIn0