@host = https://localhost:7188

POST {{host}}/api/identity/refresh
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImNhMjI5Mzk3LThkMzgtNDQ5MS05NmI2LWU3YmJjMjM5YTc5YyIsImp0aSI6IjA0Y2IyMzBmLTc4YjItNDlhYy1hMWNiLThhY2ZhZDJmNDMzYSIsImVtYWlsIjoicGFua3VuaWsyQHBhbmt1bmlrLnBsIiwiaWQiOiJjYTIyOTM5Ny04ZDM4LTQ0OTEtOTZiNi1lN2JiYzIzOWE3OWMiLCJuYmYiOjE3MDA5NTE2OTcsImV4cCI6MTcwMDk1MTk5NywiaXNzIjoic211Z2V0LWlzc3VlciIsImF1ZCI6InNtdWdldC1hdWRpZW5jZSJ9.xY6gAIDrIjt16wYkVtPNAvpPpf1oYgTXCXl73wUwInQ",
    "refreshToken": "7igAdE2p8jss5LoiHlJy+FbqWNO8FlHEo06Y6xKHY2rMDh7gu5t85tSr1VkOZq29ZLlLVAlpVxTc2G3RNNtj3g=="
}