@host = https://localhost:7188

POST {{host}}/api/identity/refresh
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImNhMjI5Mzk3LThkMzgtNDQ5MS05NmI2LWU3YmJjMjM5YTc5YyIsImp0aSI6IjcxMGE2MjNhLTdlZjUtNDRiOS04OWRmLWYzMzNiZTUxMjJmNCIsImVtYWlsIjoicGFua3VuaWsyQHBhbmt1bmlrLnBsIiwiaWQiOiJjYTIyOTM5Ny04ZDM4LTQ0OTEtOTZiNi1lN2JiYzIzOWE3OWMiLCJuYmYiOjE3MDEyODc1MDcsImV4cCI6MTcwMTI4NzgwNywiaXNzIjoic211Z2V0LWlzc3VlciIsImF1ZCI6InNtdWdldC1hdWRpZW5jZSJ9.d0Cb__3ui5mQ8fwanLOqP1Da8FFfX3pFPnqyXZjthvw",
    "refreshToken": "xVqppfOfjdXuwWIFni6Z3+994Tlan1EWiFD9x9S0vlvBXpN6nf4b66Wma0nn4LKYDIQUuOj33cddLDxMaeay7Q=="
}