# zFxRi8ZRyh4JkBEhLOLN/FdMkPsidl48SAiYRfDD/01ymVfK9Ge2paBYqzLCsj7N1YNA1QmJhrEydzi7tkp/iAuvb+HzTp6gub/PkKkhk4MzpZ5um8FvEANTYuDHyeJZ5tyq6h1o6PymgCI03y/hGkonBLGGg74QyxJmQ3TUzzU=
@host = https://localhost:7188

POST {{host}}/api/identity/refresh
Content-Type: application/json

"I77sQvigoKY9osJx31ursEOlOuB0bf9BP9f7Uawkd//xkQF5+eLy3d5EgOW2u6mkbseZj+NI7opwyMjQCWE/GU/OwJ59OVi1vSXaj+oJwDWXebRxfqsrSWLr07xbqEHNcrj1nPfx5H2JbHr1NhxCbvhW/op7a3332m/bdK88ufg="
