@host = https://localhost:7188

POST {{host}}/api/piggy-banks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImNhMjI5Mzk3LThkMzgtNDQ5MS05NmI2LWU3YmJjMjM5YTc5YyIsImp0aSI6IjRhNzExM2FhLTc3NjQtNDkwZi1iMTA5LTRjMTgzM2Y5OWI1ZCIsImVtYWlsIjoicGFua3VuaWsyQHBhbmt1bmlrLnBsIiwiaWQiOiJjYTIyOTM5Ny04ZDM4LTQ0OTEtOTZiNi1lN2JiYzIzOWE3OWMiLCJuYmYiOjE3MDA5NDg5NDksImV4cCI6MTcwMDk0OTI0OSwiaXNzIjoic211Z2V0LWlzc3VlciIsImF1ZCI6InNtdWdldC1hdWRpZW5jZSJ9.2iHsZNLDzkXf_VNwrys6Czq1UcXxe_94cuPAYLO8iM8
Content-Type: application/json

{
    "name": "My piggy bank 2",
    "withGoal": false,
    "goal": 0
}